Repository ajou-exchangers/BE, pull requests merged in 2023-12, with the labels that each got.

#14 Feat: 게시글 등록, 수정, 삭제 구현
  app.js
  controllers/boardController.js
  controllers/locationController.js
  middlewares/s3Middleware.js
  models/Comment.js
  models/Post.js
  routes/board.js
  services/boardService.js
Labels: feat

#15 Chore: Auth API 수정
  controllers/authController.js
  dto/response/LoginResponse.js
  routes/auth.js
  services/userService.js
Labels: chore

#16 Fix: post 삭제 이슈 수정
  controllers/boardController.js
  services/boardService.js
Labels: !hotfix

#17 Chore review 로그인 연동 및 로직 수정
  constants/errorMessage.js
  constants/responseMessage.js
  controllers/reviewController.js
  routes/review.js
  services/reviewService.js
Labels: chore

#19 Chore location , 수정 신청 api 예외 처리 수정
  services/locationService.js
Labels: chore

#21 Feat: 좋아요 기능 추가
  controllers/boardController.js
  routes/board.js
  services/boardService.js
Labels: feat

#23 Chore : 등록 수락하지 않은 장소 목록 조회 시 페이징 처리
  controllers/adminController.js
  services/adminService.js
Labels: chore

#25 Chore: board, comment 스키마에 updatedAt 추가, 에러 메시지 상수화하여 적용
  constants/errorMessage.js
  models/Comment.js
  models/Post.js
  services/boardService.js
  services/commentService.js
  services/reviewService.js
Labels: chore

#26 Chore: 회원 인증 로직 수정
  constants/domains.js
  constants/errorMessage.js
  controllers/authController.js
  services/authService.js
  services/userService.js
Labels: chore

#27 Feat admin
  constants/errorMessage.js
  constants/responseMessage.js
  controllers/adminController.js
  routes/admin.js
  services/adminService.js
Labels: feat

#28 Chore : 장소 수정 신청에 이유 필드 추가
  dto/location/LocationUpdateRequest.js
  models/LocationUpate.js
Labels: chore

#30 Fix: auth 에러 메시지 적용
  constants/errorMessage.js
  middlewares/authMiddleware.js
  services/authService.js
  services/boardService.js
  services/commentService.js
  services/userService.js
Labels: !hotfix

#31 Feat: 사용자 정보, 게시글 목록, 댓글 목록 조회 구현
  app.js
  controllers/adminController.js
  controllers/boardController.js
  controllers/userController.js
  dto/response/CommentListResponse.js
  dto/response/PostDetailResponse.js
  dto/response/PostListResponse.js
  dto/response/UserInfoResponse.js
  routes/user.js
  services/authService.js
  services/boardService.js
  services/userService.js
Labels: feat

#32 chore : Location 캐시 컬럼 추가
  models/Location.js
  services/locationService.js
Labels: chore

#35 Chore : Reivew api 코드 수정
  controllers/reviewController.js
  dto/review/ReviewRequest.js
  dto/review/UpdateReviewRequest.js
  services/reviewService.js
Labels: chore

#36 chore : 관리자 api 코드 정리
  controllers/adminController.js
  dto/admin/AddLocationRequest.js
  dto/admin/UpdateLocationDto.js
  dto/admin/UpdateLocationRequest.js
  services/adminService.js
Labels: chore

#37 Chore: User 스키마에 emailVerified 필드 추가 및 적용
  app.js
  models/User.js
Labels: chore

#38 Chore: User emailVerified 필드 update문 삭제
  app.js
Labels: chore

#39 Fix: 닉네임 중복확인 로직 수정
  controllers/authController.js
Labels: fix

#40 Feat: 이메일 인증 구현
  app.js
  constants/errorMessage.js
  controllers/authController.js
  middlewares/authMiddleware.js
  package-lock.json
  package.json
  routes/auth.js
  services/authService.js
  services/emailService.js
  services/userService.js
  utils/cryptoUtils.js
Labels: feat

#41 Chore: 이메일 인증 로직 수정
  services/emailService.js
  utils/cryptoUtils.js
Labels: chore

#42 Fix: 이메일 인증을 위한 crypto 로직 수정
  utils/cryptoUtils.js
Labels: fix

#43 Fix: crypto 로직 변경
  utils/cryptoUtils.js
Labels: fix

#44 chore : review crud시 트랜잭션 적용
  services/reviewService.js
Labels: chore

#45 Chore : Location Api 코드 수정 및 예외 처리 추가
  constants/errorCodes.js
  constants/errorMessage.js
  controllers/locationController.js
  services/locationService.js
  utils/LocationUtil.js
Labels: chore

#46 chore : location 등록 수락시 위도, 경도, 장소 이름이 같은 경우 추가시 예외 처리
  services/adminService.js
Labels: chore

#47 chore : 장소 추가 수정 시 장소 이름에 아주대점 수원아주대점이 존재하면 아주대학교점으로 교체
  services/locationService.js
  utils/LocationUtil.js
Labels: chore

#48 fix : 아주대점 키워드가 존재하면 아주대학교점이라고 변경후 번역 카카오맵 장소이름은 그래도 저장하도록 변경
  services/locationService.js
Labels: fix

#49 Fix: 이메일 인증 로직 수정
  services/emailService.js
  utils/cryptoUtils.js
Labels: fix

#51 Chore: Auth API에 ResponseMessage Constants 적용
  constants/responseMessage.js
  controllers/authController.js
Labels: chore

#52 Chore: 게시글 수정 로직 변경, Board, Comment API에 ResponseMessage Constants 적용
  constants/responseMessage.js
  controllers/boardController.js
  routes/board.js
  services/boardService.js
Labels: chore
