Repository ajou-exchangers/BE, pull requests merged in 2023-11, with the labels that each got.

#2 Feat location
  app.js
  constants/errorMessage.js
  constants/responseMessage.js
  controllers/locationController.js
  dto/LocationApplyRequest.js
  dto/response/Response.js
  models/Location.js
  package-lock.json
  package.json
  routes/location.js
  services/locationService.js
Labels: feat

#5 Fix: 인증, 인가 이슈 수정
  app.js
  controllers/authController.js
  services/userService.js
Labels: !hotfix

#6 chore: auth api 예외 처리 추가
  services/userService.js
Labels: chore
